### ISSUE TITLE
Celery error when importing CSV files

### ISSUE THREAD

**Issue by jefmoura** [toladata/TolaTables#501]
### Current behavior
When we try to upload a CSV file, the job never ends, so the file is uploaded but it isn't saved.

### Expected behavior
When a user uploads a CSV file, it should be uploaded and saved.

### Steps to reproduce the behavior
1. Log into Track
2. Click on `Import Data -> Import from CSV
3. Finish the process of importing

### Additional details
Environment: [**dev**/**staging**/**demo**/**production**]

```
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 99, in __init__
   self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
   self._conninfo.transport.implements.async and
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async
```

**Comment by karrla** [comment]
CSV files still don't import
@jefmoura                        
Is this the same issue (See screenshot) or should I create a new ticket.

![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/22c4f76f-a006-4ef4-97a1-c0b6187bb54c)

**Comment by jefmoura** [comment]
I had a quick look at it and it's not managing to start the celery worker. I need to look more into the issue to fix it. @karrla

**Comment by karrla** [comment]
@jefmoura 

On staging I'm still not able to import a CSV  - same issue/messge as before
![image.png](https://images.zenhubusercontent.com/58b6f81951aa2c30577726c7/5d95b0b2-76b9-40d0-970a-c4f251da3a0f)
